export const Menu: MenuItem[] = [
  {
    id: 0,
    title: 'Dashboard', 
    url: '/admin/dashboard', 
    icon: 'chart', 
    active: true,
    collapsedTemplate: '<span class="collapsed-item"><i class="dx-icon dx-icon-chart dx-list-item-icon"></i></span>'
  },
  {
    id: 1,
    title: 'Manage Categories', 
    url: '/admin/manage-categories', 
    icon: 'hierarchy', 
    active: false,
    collapsedTemplate: '<span class="collapsed-item"><i class="dx-icon dx-icon-hierarchy dx-list-item-icon"></i></span>'
  },
  {
    id: 2,
    title: 'Manage Orders', 
    url: '/admin/manage-orders', 
    icon: 'cart', 
    active: false,
    collapsedTemplate: '<span class="collapsed-item"><i class="dx-icon dx-icon-cart dx-list-item-icon"></i></span>'
  },
  {
    id: 3,
    title: 'Manage Products', 
    url: '/admin/manage-products', 
    icon: 'product', 
    active: false,
    collapsedTemplate: '<span class="collapsed-item"><i class="dx-icon dx-icon-product dx-list-item-icon"></i></span>'
  },
  {
    id: 4,
    title: 'Specification Fields', 
    url: '/admin/spec-fields', 
    icon: 'detailslayout', 
    active: false,
    collapsedTemplate: '<span class="collapsed-item"><i class="dx-icon dx-icon-detailslayout dx-list-item-icon"></i></span>'
  }
];

export interface MenuItem {
    id: number;
    icon?: string;
    title: string;
    url?: string | undefined;
    collapsedTemplate?: string;
    active?: boolean;
    subMenuItems?: MenuItem[] | undefined;
}

export enum BaseURL {
  LoginPage = 'auth/login',
  AdminURL = 'admin',
  PortalURL = 'portal'
}

export enum AdminPage {
  ManageCategories = 'manage-categories',
  ManageProducts = 'manage-products',
  ManageOrders = 'manage-orders',
  SpecificationFields = 'spec-fields'
}

export enum PortalPage {
  Products = 'products'
}

export const AdPopuplist = [
  {
    id: 'point-gifts',
    text: 'Buy though our app and get usable free points in all our stores'
  },
  {
    id: 'discounts',
    text: 'We always have amazing discounts on our products all year long'
  },
  {
    id: 'multi-national',
    text: 'We have the best quality products from international brands from all over the world'
  }
];

export const Countries = ['Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Antarctic Territory',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Canton and Enderbury Islands',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos [Keeling] Islands',
  'Colombia',
  'Comoros',
  'Congo - Brazzaville',
  'Congo - Kinshasa',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Côte d’Ivoire',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Dronning Maud Land',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'French Southern and Antarctic Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Honduras',
  'Hong Kong SAR China',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Johnston Island',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau SAR China',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Metropolitan France',
  'Mexico',
  'Micronesia',
  'Midway Islands',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar [Burma]',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'Neutral Zone',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'North Vietnam',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pacific Islands Trust Territory',
  'Pakistan',
  'Palau',
  'Palestinian Territories',
  'Panama',
  'Panama Canal Zone',
  'Papua New Guinea',
  'Paraguay',
  'People\'s Democratic Republic of Yemen',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'São Tomé and Príncipe',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'U.S. Minor Outlying Islands',
  'U.S. Miscellaneous Pacific Islands',
  'U.S. Virgin Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Unknown or Invalid Region',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Wake Island',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands']